
login:
  url: /login/:type/*
  param: { module: facebook_login, action: login }


# default rules
homepage:
  url:   /
  param: { module: top, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
